resource "aws_iam_policy" "this" {
  name        = var.name
  description = "Policy generated by module"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = concat(
      length(var.queue_arns) > 0 ? [{
        Sid      = "AllowSQS"
        Effect   = "Allow"
        Action   = [
          "sqs:ReceiveMessage",
          "sqs:DeleteMessage",
          "sqs:GetQueueAttributes"
        ]
        Resource = var.queue_arns
      }] : [],
      var.kms_key_arn != null ? [{
        Sid      = "AllowKMS"
        Effect   = "Allow"
        Action   = [
          "kms:Decrypt"
        ]
        Resource = var.kms_key_arn
      }] : []
    )
  })
}
